### ISSUE TITLE
File "process.py", line 3, in <module> - NameError: name '_winreg' is not defined

### ISSUE THREAD

**Issue by doroshko** [yaa110/Adobe-Air-Registry-Modifier#2]
I had successfully compiled it, but nothing works.

An _output is:
```javascript
Traceback (most recent call last):
  File "process.py", line 3, in <module>
NameError: name '_winreg' is not defined
```

Did you try it yourself, does it work?

**Comment by yaa110** [comment]
I checked the code and it works fine. However, you can download executable file of python.py from [here](https://github.com/yaa110/Adobe-Air-Registry-Modifier/releases)

**Comment by doroshko** [comment]
I had successfully compiled it on other PC. Same as yours exe.
I placed your exe to the root D:\
Same error occurs:
```javascript
D:\>process -action:read -key:"URL Protocol" -path:callto -rootkey:HKEY_CLASSES_ROOT
Traceback (most recent call last):
  File "process.py", line 3, in <module>
NameError: name '_winreg' is not defined
```

**Comment by BS2732** [comment]
I get the same error when using this program in my air app.

**Comment by xotlr43** [comment]
I got error too :-(

**Comment by mfares** [comment]
i figured out how to fix it:
`import _winreg as winreg
import sys
# switch (rootkey)
root_keys = {
             "HKEY_LOCAL_MACHINE" : winreg.HKEY_LOCAL_MACHINE,
             "HKEY_CLASSES_ROOT" : winreg.HKEY_CLASSES_ROOT,
             "HKEY_CURRENT_CONFIG" : winreg.HKEY_CURRENT_CONFIG,
             "HKEY_CURRENT_USER" : winreg.HKEY_CURRENT_USER,
             "HKEY_USERS" : winreg.HKEY_USERS
             }

def read_key():
    try:
        hKey = winreg.OpenKey(root_keys[rk.upper()], p)
        _value, _type = winreg.QueryValueEx (hKey, k)
        sys.stdout.write(str(_value))
    except Exception as e:
        sys.stderr.write("Error: " + str(e))

def write_key():
    try:
        key = winreg.CreateKey(root_keys[rk.upper()], p)
        winreg.SetValueEx(key, k, 0, winreg.REG_SZ, v)
        sys.stdout.write('Key has been created.')
    except Exception as e:
        sys.stderr.write("Error: " + str(e))

def write_key_dword():
    try:
        key = winreg.CreateKey(root_keys[rk.upper()], p)
        winreg.SetValueEx(key, k, 0, winreg.REG_DWORD, v)
        sys.stdout.write('DWORD Key has been created.')
    except Exception as e:
        sys.stderr.write("Error: " + str(e))

def delete_key():
    try:
        winreg.DeleteKey(root_keys[rk.upper()], p)
        sys.stdout.write('Key has been deleted.')
    except Exception as e:
        sys.stderr.write("Error: " + str(e))

def check_key():
    aReg = winreg.ConnectRegistry(None,root_keys[rk.upper()])
    aKey = winreg.ConnectRegistry(None,root_keys[rk.upper()])
    try:
        aKey = winreg.OpenKey(aReg, p, 0)
    except Exception as e:
        sys.stderr.write("Error: " + str(e))
    else:
        sys.stdout.write('exists')
        
    winreg.CloseKey(aKey)
    winreg.CloseKey(aReg)


# switch (action)
actions = {
           "read" : read_key,
           "write" : write_key,
           "writedword" : write_key_dword,
           "delete" : delete_key,
           "check" : check_key,
           }

# Get arguments
for i in sys.argv:
    try:
        if i.find("-key") != -1: k = i.split(":")[1]
        elif i.find("-value") != -1: v = i.split(":")[1]
        elif i.find("-path") != -1: p = i.split(":")[1]
        elif i.find("-rootkey") != -1: rk = i.split(":")[1]
        elif i.find("-action") != -1: a = i.split(":")[1]
    except Exception as e:
        sys.stderr.write("Invalid argument: " + str(e))

try:
    actions[a.lower()]()
except Exception as e:
    sys.stderr.write("Invalid action " + a.lower() + ": " + str(e))
`

**Comment by yaa110** [comment]
Thank you @mfares 
Please note that the _winreg module has been renamed to winreg in Python 3
